import "@/app/globals.css";
import { Lato } from "next/font/google";
import Nav from "@/components/navigation/nav";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "E-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(`${lato.variable} font-sans antialiased`)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex flex-col min-h-screen">
            <header className="w-full">
              <Nav />
            </header>
            <main className="mx-auto p-8">{children}</main>
            <footer className="bottom-0 absolute bg-primary/30 p-4 w-full" />
          </div>
          <Toaster richColors closeButton expand={true} />
        </ThemeProvider>
      </body>
    </html>
  );
}
