import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/navigation/nav";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "flex flex-col min-h-screen",
          `${geistSans.variable} ${geistMono.variable} antialiased`
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header>
            <Nav />
          </header>
          <main className="flex flex-col gap-4 px-2">{children}</main>
          <footer className="mt-auto">FOOTER</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
